name: StaffChat
version: '${project.version}'
main: me.jojojelte.staffchat.Main
api-version: 1.17
authors: [jojojelte]
description: A simple staffchat plugin to communicate with staff.
website: jeltevdv.nl
commands:
  sc:
    description: Use the staffchat!
    usage: /sc [message]
    aliases: [staffchat]
  screload:
    description: Reload the config!
    usage: /screload
    aliases: [staffchatreload, scr]
  ac:
    description: Use the adminchat!
    usage: /ac [message]
    aliases: [adminchat]
permissions:
  staffchat.staffchat:
    description: Use the staffchat
  staffchat.adminchat:
    description: Use the adminchat
  staffchat.reload:
    description: Relaod config
  staffchat.*:
    description: Use all commands